# -*- coding: utf-8 -*-
"""Network security.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rRRul7bOad5mK2rL29z0mnB1wEU6-aan
"""

import hashlib 

text=input("Please Enter word : ")
hash_obj = hashlib.md5(text.encode())
md5_hash = hash_obj.hexdigest()
print(md5_hash)